// <auto-generated />
namespace Tracking.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AttendenceTracking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttendenceTracking));
        
        string IMigrationMetadata.Id
        {
            get { return "201808210928350_AttendenceTracking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
